version: "3.2" #Version de Docker compose que estamos utilizando
services: #Servicios, es decir, los contenedores que vamos a crear
  cliente: #Nombre del contenedor
    build: . #Indicamos que este contenedor se va a construrir a traves del Dockerfile
    ports: #Vamos a indicar una lista de los puertos que vamos a mapear para el contenedor
      - "8080:8080" #PuertoDelHost:PuertoDelContenedor
    links: #Lista con los contenedores a los que el contenedor se va a conectar
      - postgres_test #Este es el nombre del contenedor
  postgres_test: #Nombre del contenedor
    image: postgres #Imagen desde la cual vamos a construir el contenedor
    environment: #Variables de entorno que hay que configurar en la maquina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contrasena
      POSTGRES_DB: test
